apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    name: antoniosql-nfs
  name: antoniosql-nfs
  namespace: antonio
spec:
  replicas: 1
  selector:
    name: antoniosql-nfs
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        name: antoniosql-nfs
    spec:
      containers:
        - name: antoniosql-nfs
          image: mysql:5.6
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: pv-antonio-nfs
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test
          ports:
            - containerPort: 3306
              protocol: TCP
      volumes:
        - name: pv-antonio-nfs
          persistentVolumeClaim:
            claimName: pvc-antonio-nfs
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - antoniosql-nfs
      from:
        kind: ImageStreamTag
        name: mysql:5.6
        namespace: openshift
      lastTriggeredImage: 172.30.1.1:5000/openshift/mysql@sha256:ad629a897185728349b33073300bb657303a0df14067bab323d72416e31f4f0f
    type: ImageChange
