apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: antonio-mysql-nfs
    name: antonio-mysql-nfs
    namespace: antonio2
  spec:
    clusterIP: 172.30.51.149
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: antonio-mysql-nfs
      deploymentconfig: antonio-mysql-nfs
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: safiebine
    name: safiebine
    namespace: antonio2
  spec:
    clusterIP: 172.30.228.11
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: safiebine
      deploymentconfig: safiebine
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 3
    labels:
      app: antonio-mysql-nfs
    name: antonio-mysql-nfs
    namespace: antonio2
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: antonio-mysql-nfs
      deploymentconfig: antonio-mysql-nfs
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: antonio-mysql-nfs
          deploymentconfig: antonio-mysql-nfs
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: test
          image: 172.30.1.1:5000/openshift/mysql@sha256:ad629a897185728349b33073300bb657303a0df14067bab323d72416e31f4f0f
          imagePullPolicy: IfNotPresent
          name: antonio-mysql-nfs
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: pv-antonio-nfs2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: pv-antonio-nfs2
          persistentVolumeClaim:
            claimName: pvc-antonio-nfs2
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - antonio-mysql-nfs
        from:
          kind: ImageStreamTag
          name: mysql:5.6
          namespace: openshift
        lastTriggeredImage: 172.30.1.1:5000/openshift/mysql@sha256:ad629a897185728349b33073300bb657303a0df14067bab323d72416e31f4f0f
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 17
    labels:
      app: safiebine
    name: safiebine
    namespace: antonio2
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: safiebine
      deploymentconfig: safiebine
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: safiebine
          deploymentconfig: safiebine
      spec:
        containers:
        - env:
          - name: DB
            valueFrom:
              configMapKeyRef:
                key: host
                name: new-config-map
          - name: USER
            valueFrom:
              configMapKeyRef:
                key: user
                name: new-config-map
          - name: PASS
            valueFrom:
              configMapKeyRef:
                key: password
                name: new-config-map
          - name: DATAB
            valueFrom:
              configMapKeyRef:
                key: database
                name: new-config-map
          image: 172.30.1.1:5000/antonio2/safiebine@sha256:b6b944a4009965b079ba9a30cd78388c9fee40165a9dba3aaeac90cd4f659af1
          imagePullPolicy: Always
          name: safiebine
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - safiebine
        from:
          kind: ImageStreamTag
          name: safiebine:latest
          namespace: antonio2
        lastTriggeredImage: 172.30.1.1:5000/antonio2/safiebine@sha256:b6b944a4009965b079ba9a30cd78388c9fee40165a9dba3aaeac90cd4f659af1
      type: ImageChange
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: safiebine
    name: safiebine
    namespace: antonio2
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: safiebine:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: final_project/app
      git:
        uri: https://github.com/antonioalexandru/DO288-apps
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:10
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: uG337tHAYJTUeMunxpXw
      type: GitHub
    - generic:
        secret: PY-YNE717fiVInanz8RM
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: 172.30.1.1:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2020-03-09T12:02:03Z
    generation: 2
    name: antonio-mysql-nfs
    namespace: antonio2
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/openshift/mysql:5.6
      generation: 2
      importPolicy: {}
      name: "5.6"
      referencePolicy:
        type: Source
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: safiebine
    name: safiebine
    namespace: antonio2
  spec:
    lookupPolicy:
      local: false
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
