apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: antoniosql-nfs
  name: pv-antonio-nfs2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-antonio-nfs2
    namespace: antonio2
  nfs:
    path: /database/new2
    server: mopbzp174145.fr.dst.ibm.com
  persistentVolumeReclaimPolicy: Retain
