apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-antonio-nonfs
  labels:
    app: antoniosql-nonfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage/data2
    type: ""
  persistentVolumeReclaimPolicy: Retain
