apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-antonio-nfs2
  labels:
    name: antoniosql-nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /database/new2
    server: mopbzp174145.fr.dst.ibm.com
