apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-antonio-nfs2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: antoniosql-nfs
