apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-antonio-nonfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: antoniosql-nonfs
